from typing import Any

class Schemas:
    schemas: Any
    pretty: Any
    def __init__(self, discovery) -> None: ...
    def prettyPrintByName(self, name): ...
    def prettyPrintSchema(self, schema): ...
    def get(self, name, default: Any | None = ...): ...

class _SchemaToStruct:
    value: Any
    string: Any
    schema: Any
    dent: Any
    from_cache: Any
    seen: Any
    def __init__(self, schema, seen, dent: int = ...) -> None: ...
    def emit(self, text) -> None: ...
    def emitBegin(self, text) -> None: ...
    def emitEnd(self, text, comment) -> None: ...
    def indent(self) -> None: ...
    def undent(self) -> None: ...
    def to_str(self, from_cache): ...
