import typing

import typing_extensions

class Groups(typing_extensions.TypedDict, total=False):
    whoCanAdd: str
    archiveOnly: str
    sendMessageDenyNotification: str
    allowExternalMembers: str
    whoCanApproveMessages: str
    includeCustomFooter: str
    kind: str
    whoCanTakeTopics: str
    whoCanModerateMembers: str
    whoCanApproveMembers: str
    whoCanMoveTopicsOut: str
    favoriteRepliesOnTop: str
    maxMessageBytes: int
    whoCanUnmarkFavoriteReplyOnAnyTopic: str
    whoCanDeleteAnyPost: str
    primaryLanguage: str
    whoCanModerateContent: str
    whoCanViewGroup: str
    whoCanDiscoverGroup: str
    whoCanPostAnnouncements: str
    messageModerationLevel: str
    customReplyTo: str
    showInGroupDirectory: str
    whoCanUnassignTopic: str
    whoCanMarkFavoriteReplyOnAnyTopic: str
    whoCanJoin: str
    whoCanBanUsers: str
    whoCanModifyMembers: str
    whoCanMakeTopicsSticky: str
    includeInGlobalAddressList: str
    name: str
    whoCanMoveTopicsIn: str
    whoCanContactOwner: str
    whoCanInvite: str
    description: str
    whoCanPostMessage: str
    whoCanAddReferences: str
    whoCanAssistContent: str
    whoCanAssignTopics: str
    whoCanModifyTagsAndCategories: str
    whoCanMarkFavoriteReplyOnOwnTopic: str
    isArchived: str
    whoCanMarkDuplicate: str
    whoCanLockTopics: str
    whoCanLeaveGroup: str
    spamModerationLevel: str
    whoCanEnterFreeFormTags: str
    email: str
    whoCanViewMembership: str
    customFooterText: str
    replyTo: str
    membersCanPostAsTheGroup: str
    messageDisplayFont: str
    whoCanMarkNoResponseNeeded: str
    enableCollaborativeInbox: str
    whoCanHideAbuse: str
    allowWebPosting: str
    allowGoogleCommunication: str
    whoCanDeleteTopics: str
    customRolesEnabledForSettingsToBeMerged: str
    defaultMessageDenyNotificationText: str
