name: Publish to PyPi

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      
    - name: Install Poetry
      run: pip install poetry
      
    - name: Build and publish
      run: poetry publish --build --username __token__ --password "$PYPI_TOKEN"
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
